# Generated by Django 5.1.7 on 2025-10-19 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tridentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
