# Generated by Django 5.2.7 on 2025-10-19 23:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridentapp', '0002_rename_name_product_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchasers',
            field=models.ManyToManyField(blank=True, related_name='purchased_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
