# Generated by Django 5.1.7 on 2025-10-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridentapp', '0004_remove_product_units_event_livestream_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='livestream_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Livestream',
        ),
    ]
