# Generated by Django 5.1.7 on 2025-10-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tridentapp', '0005_event_livestream_url_delete_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
